const sider = {
  en: {
    home: 'Home',
    popular: 'Popular',
    answers: 'Answers',
    explore: 'Explore',
    all: 'All',
    create_community: 'Create a community',
    community: 'Community',
    resources: 'Resources',
    about: 'About Youth-Pai',
    advertisement: 'Advertisement',
    youth_pro: 'Youth Pro',
    help: 'Help',
    blog: 'Blog',
    careers: 'Careers',
  },
  zh: {
    home: '首页',
    popular: '热门最新',
    answers: '问答专区',
    explore: '发现',
    all: '所有内容',
    create_community: '创建社区',
    community: '社区小圈',
    resources: '资源库',
    about: '关于 Youth-Pai',
    advertisement: '广告',
    youth_pro: '青年计划',
    help: '帮助',
    blog: '博客',
    careers: '职业',
  }
}
export default sider
