const authRegister = {
  en: {
    BackHome: 'Back to home',
    RegisterTitle: 'Create Youth-π Account',
    RegisterSubtitle: 'Join us and start your new journey',
    Email: 'Email Address',
    InputEmail: 'Please enter your email address',
    Password: 'Password',
    InputPassword: 'Please enter your password',
    ConfirmPassword: 'Confirm Password',
    InputConfirmPassword: 'Please re-enter your password',
    VerificationCode: 'Verification Code',
    InputVerificationCode: 'Please enter the verification code',
    SendCode: 'Send Code',
    RegisterButton: 'Sign up',
    AlreadyHaveAccount: 'Already have an account?',
    LoginLink: 'Sign in now',
  },
  zh: {
    BackHome: '回到主页',
    RegisterTitle: '创建 Youth Pai 账号',
    RegisterSubtitle: '加入我们，开启你的新旅程',
    Email: '邮箱地址',
    InputEmail: '请输入邮箱地址',
    Password: '密码',
    InputPassword: '请输入密码',
    ConfirmPassword: '确认密码',
    InputConfirmPassword: '请再次输入密码',
    VerificationCode: '验证码',
    InputVerificationCode: '请输入验证码',
    SendCode: '发送验证码',
    RegisterButton: '注册',
    AlreadyHaveAccount: '已经有账号了？',
    LoginLink: '立即登录',
  }
}
export default authRegister
